servers:
  hosts:
    vm1:
      ansible_user: vm1
      ansible_host: 192.168.124.201
  vars:
    ansible_password: 2369180ho
    ansible_become_pass: 2369180ho

clients:
  hosts:
    vm2:
      ansible_user: vm2
      ansible_host: 192.168.124.204
  vars:
    ansible_password: 2369180ho
    ansible_become_pass: 2369180ho
