---
- name: install velociraptor 0.72.4 linux amd64 on hosts
  hosts: servers
  become: yes
  vars_files:
    - vault.yml
  tasks:
    - name: ensure required packages are installed
      dnf:
        name:
          - wget
        state: present

    - name: create velociraptor opt directory if it does not exist
      file:
        path: /opt/velociraptor
        state: directory
        mode: '0755'

    - name: create velociraptor etc directory if it does not exist
      file:
        path: /etc/velociraptor
        state: directory
        mode: '0755'

    - name: download velociraptor binary
      get_url:
        url: https://github.com/Velocidex/velociraptor/releases/download/v0.72/velociraptor-v0.72.4-linux-amd64
        dest: /opt/velociraptor/velociraptor
        mode: '0755'

    - name: verify velociraptor binary is downloaded
      stat:
        path: /opt/velociraptor/velociraptor
      register: velociraptor_file

    - name: create server's config
      shell: |
        /opt/velociraptor/velociraptor config generate --merge \
          '{
            "Client": {
              "server_urls": ["https://{{ansible_default_ipv4.address}}:443/"],
              "use_self_signed_ssl": true
            },
            "API": {
              "hostname": "{{ansible_default_ipv4.address}}",
              "bind_address": "0.0.0.0",
              "bind_port": 8001
            },
            "GUI": {
              "bind_address": "0.0.0.0",
              "bind_port": 80,
              "initial_users": [
                {
                  "name": "LisDem",
                  "password_hash": "74d5e17c96d70cc98fa052de1c9a81bfc95cb248e9df97d2a1ba7961d5b756d4",
                  "password_salt": "42dffe7dfd846796debd054a6fa580dc4d2ec0cc8fb0485a524872ae3bd2c023"
                }
              ]
            },
            "Frontend": {
              "hostname": "{{ansible_default_ipv4.address}}",
              "bind_address": "0.0.0.0",
              "bind_port": 443
            }
          }' > /etc/velociraptor/server.config.yaml
      when: velociraptor_file.stat.exists

    - name: generate server's rpm package
      shell: /opt/velociraptor/velociraptor --config /etc/velociraptor/server.config.yaml rpm server --output /opt/velociraptor/velociraptor-server-0.72.4.x86_64.rpm

    - name: generate client's rpm package
      shell: /opt/velociraptor/velociraptor --config /etc/velociraptor/server.config.yaml rpm client --output /opt/velociraptor/velociraptor-client-0.72.4.x86_64.rpm
    
    - name: install server's RPM package if not installed
      dnf:
        name: /opt/velociraptor/velociraptor-server-0.72.4.x86_64.rpm
        state: present
        disable_gpg_check: yes

    - name: install client's RPM package if not installed
      dnf:
        name: /opt/velociraptor/velociraptor-client-0.72.4.x86_64.rpm
        state: present
        disable_gpg_check: yes

    - name: Change ownership of inventory.json.db
      file:
        path: /var/tmp/velociraptor/config/inventory.json.db
        owner: velociraptor
        group: velociraptor
        state: file

    - name: restart velociraptor_server service
      systemd:
        name: velociraptor_server.service
        state: restarted

    - name: Check if firewalld is active
      command: "systemctl is-active firewalld"
      register: firewalld_status
      ignore_errors: yes

    - name: Check if iptables is active
      command: "iptables -L"
      register: iptables_status
      ignore_errors: yes

    - name: Check if nftables is active
      command: "nft list ruleset"
      register: nftables_status
      ignore_errors: yes

    - name: Allow HTTP (port 80) in firewalld
      firewalld:
        zone: public
        port: 80/tcp
        state: enabled
        permanent: yes
      when: firewalld_status.stdout == "active"

    - name: Allow HTTPS (port 443) in firewalld
      firewalld:
        zone: public
        port: 443/tcp
        state: enabled
        permanent: yes
      when: firewalld_status.stdout == "active"

    - name: Allow HTTP (port 80) in iptables
      iptables:
        chain: INPUT
        protocol: tcp
        destination_port: 80
        jump: ACCEPT
      when: iptables_status.rc == 0 and firewalld_status.rc != 0

    - name: Allow HTTPS (port 443) in iptables
      iptables:
        chain: INPUT
        protocol: tcp
        destination_port: 443
        jump: ACCEPT
      when: iptables_status.rc == 0 and firewalld_status.rc != 0

    - name: Allow HTTP (port 80) in nftables
      command: "nft add rule ip filter input tcp dport 80 accept"
      when: nftables_status.rc == 0 and firewalld_status.rc != 0 and iptables_status.rc != 0

    - name: Allow HTTPS (port 443) in nftables
      command: "nft add rule ip filter input tcp dport 443 accept"
      when: nftables_status.rc == 0 and firewalld_status.rc != 0 and iptables_status.rc != 0

    - name: Reload firewalld if it is active
      command: "systemctl reload firewalld"
      when: firewalld_status.stdout == "active"

    - name: Ensure /etc/iptables directory exists if iptables is active
      file:
        path: /etc/iptables
        state: directory
      when: iptables_status.rc == 0 and firewalld_status.rc != 0

    - name: Save iptables rules if active
      shell: "iptables-save > /etc/iptables/rules.v4"
      when: iptables_status.rc == 0 and firewalld_status.rc != 0

    - name: Ensure /etc/nftables directory exists if nftables is active
      file:
        path: /etc/nftables
        state: directory
      when: nftables_status.rc == 0 and firewalld_status.rc != 0 and iptables_status.rc != 0

    - name: Save nftables rules if active
      shell: "nft list ruleset > /etc/nftables/rules.v4"
      when: nftables_status.rc == 0 and firewalld_status.rc != 0 and iptables_status.rc != 0

    - name: copying the client package
      fetch:
        src: /opt/velociraptor/velociraptor-client-0.72.4.x86_64.rpm
        dest: /tmp/
        flat: yes