servers:
  hosts:
    vm1:
      ansible_user: vm1
      ansible_host: 192.168.124.201
      ansible_ssh_pass: "{{ vm1.password }}"
      ansible_become_pass: "{{ vm1.become_pass }}"
clients:
  hosts:
    vm2:
      ansible_user: vm2
      ansible_host: 192.168.124.204
      ansible_ssh_pass: "{{ vm2.password }}"
      ansible_become_pass: "{{ vm2.become_pass }}"
