---
- name: Remove rule to allow HTTP (port 8080)
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: 8080
    jump: ACCEPT
    state: absent

- name: Remove rule to allow HTTPS (port 8443)
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: 8443
    jump: ACCEPT
    state: absent