---
- name: Remove rule to allow HTTP (port 80)
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: 80
    jump: ACCEPT
    state: absent

- name: Remove rule to allow HTTPS (port 443)
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: 443
    jump: ACCEPT
    state: absent