---
- name: Allow HTTP (port 80)
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: 8080
    jump: ACCEPT

- name: Allow HTTPS (port 443)
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: 8443
    jump: ACCEPT