---
- name: copying the RPM package to client machines
  copy:
    src: /tmp/velociraptor-client-0.72.4.x86_64.rpm
    dest: /tmp/velociraptor-client-0.72.4.x86_64.rpm

- name: installing the RPM package
  dnf:
    name: /tmp/velociraptor-client-0.72.4.x86_64.rpm
    state: present
    disable_gpg_check: yes